project:
  type: website

website:
  title: "bits.lanzinger.space"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MDornacher/
format:
  html:
    theme: cosmo
    css: styles.css
